[package]
name = "duplex"
version = "0.1.0"
edition = "2018"

[dependencies]
nom = "4.1.1"
lazy_static = "1.2.0"
serde = { version = "1.0.82", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true
