export default [
    { name: 'sune', moves: `R U R' U R U2 R'`, mirror: true, invert: true },
    { name: 'dblsune', moves: `R U R' U R U' R' U R U2 R'`, mirror: true, invert: true },
    { name: 'widesune', moves: `r U R' U R U2 r'`, mirror: true, invert: true },
    { name: 'dblwidesune', moves: `r U R' U R U' R' U R U2 r'`, mirror: true, invert: true },
    { name: 'pureflip', moves: `RUR2FRF'y'R'UR`, mirror: true, invert: true },
    { name: 'suneflip', moves: `RU2R'U2R'FRF'`, mirror: true, invert: true },
    { name: 'fruruf', moves: `FRUR'U'F'`, mirror: true, invert: true },
    { name: 'dlbfruruf', moves: `F R U R' U' R U R' U' F'`, mirror: true, invert: true },
    { name: 'aperm', moves: `l'UR'D2RU'R'D2R2x'`, mirror: true, invert: true },
    { name: 'tperm', moves: `RUR'U'R'FR2U'R'U'RUR'F'`, mirror: false, invert: false },
    { name: 'sexysledge', moves: `R U R' U' R' F R F'`, mirror: true, invert: true },
    { name: 'uperm', moves: `M2 U'MU2M'U'M2`, mirror: true, invert: true },
    { name: 'sexyslice', moves: `R U R' U' M' URU' r'`, mirror: true, invert: true },
    { name: 'edgeflip', moves: `M'U'MU2M'U'M`, mirror: true, invert: true },
    { name: 'unnamed', moves: `r U' r' U' r U r' F' U F`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R' U' R' F R F' U R`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R U' R D R' U2 R D' R2 U' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R2 D R' U2 R D' R' U2 R'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R2 D R' U R D' R2 U' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R U' L' U R' U L U L' U L`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R' U' R U' R' U F' U F R`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R' U' R' F R F' R U' R' U2 R`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R U2 R' U2 R' F R2 U R' U' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R U' R' U' R U2 R' U' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R' U' R U R' F' R U R' U' R' F R2`, mirror: true, invert: true },
    { name: 'unnamed', moves: `r U r' R U R' U' r U' r'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R U R' U R U' R' U' R' F R F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F U R U2 R' U' R U R' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R U R' U' R U' R' U R U R' F'`, mirror: true, invert: true },
];
