export default [
    { name: 'sune', moves: `R U R' U R U2 R'`, mirror: true, invert: true },
    { name: 'doublesune', moves: `R U R' U R U' R' U R U2 R'`, mirror: true, invert: true },
    { name: 'widesune', moves: `r U R' U R U2 r'`, mirror: true, invert: true },
    { name: 'doublewidesune', moves: `r U R' U R U' R' U R U2 r'`, mirror: true, invert: true },
    { name: 'sune H', moves: `RUR'UR'U'R2U'R2U2R`, mirror: true, invert: true },
    { name: 'suneflip', moves: `RU2R'U2R'FRF'`, mirror: true, invert: true },
    { name: 'pureflip', moves: `RUR2FRF'y'R'UR`, mirror: true, invert: true },
    { name: 'niklas', moves: `RU'L'UR'U'L`, mirror: true, invert: true },
    { name: 'bruno', moves: `RU2R2U'R2U'R2U2R`, mirror: true, invert: true },
    { name: 'fruruf', moves: `FRUR'U'F'`, mirror: true, invert: true },
    { name: 'doublefruruf', moves: `F R U R' U' R U R' U' F'`, mirror: true, invert: true },
    { name: 'widefruruf', moves: `fRUR'U'f'`, mirror: true, invert: true },
    { name: 'aperm', moves: `xR'UR'D2RU'R'D2R2x'`, mirror: true, invert: true },
    { name: 'tperm', moves: `RUR'U'R'FR2U'R'U'RUR'F'`, mirror: false, invert: false },
    { name: 'sexysledge', moves: `R U R' U' R' F R F'`, mirror: true, invert: true },
    { name: 'uperm', moves: `M2 U'MU2M'U'M2`, mirror: true, invert: true },
    { name: 'sexyslice', moves: `R U R' U' M' URU' r'`, mirror: true, invert: true },
    { name: 'edgeflip', moves: `M'U'MU2M'U'M`, mirror: true, invert: true },
    { name: 'diag U', moves: `FU'R'URUF'R'U2R`, mirror: true, invert: true },
    { name: 'diagsune', moves: `RUR'UR'FRF'RU2R'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `r U' r' U' r U r' F' U F`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R' U' R' F R F' U R`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R U' R D R' U2 R D' R2 U' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R2 D R' U2 R D' R' U2 R'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R2 D R' U R D' R2 U' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R U' L' U R' U L U L' U L`, mirror: true, invert: true },
    { name: 'sad bruno', moves: `R' U' R U' R' U F' U F R`, mirror: true, invert: true },
    { name: 'happy bruno', moves: `R' U' R' F R F' R U' R' U2 R`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R U2 R' U2 R' F R2 U R' U' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R U' R' U' R U2 R' U' F'`, mirror: true, invert: true },
    { name: 'asdf', moves: `R' U' R U R' F' R U R' U' R' F R2`, mirror: true, invert: true },
    { name: 'unnamed', moves: `r U M U R' U' r U' r'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `R U R' U R U' R' U' R' F R F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F U R U2 R' U' R U R' F'`, mirror: true, invert: true },
    { name: 'unnamed', moves: `F R U R' U' R U' R' U R U R' F'`, mirror: true, invert: true },
    { name: 'OLL17', moves: `R U R' U R' F R F' U2 R' F R F'`, mirror: true, invert: true },
    { name: 'other', moves: `R' U' F U R U' R' F' R`, mirror: true, invert: true },
];
