export default [
    { name: 'sune', moves: `R U R' U R U2 R'`, mirror: 'FB', invert: true },
    { name: 'doublesune', moves: `R U R' U R U' R' U R U2 R'`, mirror: 'FB', invert: true },
    { name: 'widesune', moves: `r U R' U R U2 r'`, mirror: 'FB', invert: true },
    { name: 'doublewidesune', moves: `r U R' U R U' R' U R U2 r'`, mirror: 'FB', invert: true },
    { name: 'suneH', moves: `RUR'UR'U'R2U'R2U2R`, mirror: 'FB', invert: true },
    { name: 'suneflip', moves: `RU2R'U2R'FRF'`, mirror: 'FB', invert: true },
    { name: 'sunesledge', moves: `R U R' U R U' R' U' R' F R F'`, mirror: 'FB', invert: true },
    { name: 'kitsune', moves: `F U R U2 R' U' R U R' F'`, mirror: 'FB', invert: true },
    { name: 'pureflip', moves: `RUR2FRF'y'R'UR`, mirror: 'FB', invert: true },
    { name: 'niklas', moves: `RU'L'UR'U'L`, mirror: 'FB', invert: true },
    { name: 'fruf', moves: `FRUR'U'F'`, mirror: 'LR', invert: true },
    { name: 'doublefruf', moves: `F R U R' U' R U R' U' F'`, mirror: 'LR', invert: true },
    { name: 'widefruf', moves: `fRUR'U'f'`, mirror: 'LR', invert: true },
    { name: 'Uperm', moves: `M2 U'MU2M'U'M2`, mirror: null, invert: true },
    { name: 'Tperm', moves: `RUR'U'R'FR2U'R'U'RUR'F'`, mirror: null, invert: false },
    { name: 'sexyslice', moves: `R U R' U' M' URU' r'`, mirror: 'FB', invert: true },
    { name: 'sexysledge', moves: `R U R' U' R' F R F'`, mirror: 'FB', invert: true },
    { name: 'edgeflip', moves: `M'U'MU2M'U'M`, mirror: 'FB', invert: true },
    { name: 'niklasflip', moves: `r U' r' U' r U r' F' U F`, mirror: 'FB', invert: true },
    { name: 'snapfruf', moves: `R' U' R' F R F' U R`, mirror: 'FB', invert: true },
    { name: 'diagU', moves: `FU'R'URUF'R'U2R`, mirror: 'FB', invert: true },
    { name: 'diagsune', moves: `RUR'UR'FRF'RU2R'`, mirror: 'FB', invert: true },
    { name: 'niklasune', moves: `R U' L' U R' U L U L' U L`, mirror: 'FB', invert: true },
    { name: 'sledgesune', moves: `R' U' R' F R F' R U' R' U2 R`, mirror: 'FB', invert: true },
    { name: 'doublesledge', moves: `R U R' U R' F R F' U2 R' F R F'`, mirror: 'LR', invert: true },
    { name: 'tswap', moves: `F R U' R' U' R U2 R' U' F'`, mirror: 'FB', invert: true },
    { name: 'almostJ', moves: `R' U' R U R' F' R U R' U' R' F R2`, mirror: 'FB', invert: true },
    { name: 'fspam', moves: `F R U R' U' R U' R' U R U R' F'`, mirror: 'FB', invert: true },
    { name: 'cake', moves: `R' U' F U R U' R' F' R`, mirror: 'FB', invert: true },
    { name: 'fruit', moves: `F R U R' U' R F' r U R' U' r'`, mirror: 'FB', invert: true },
    { name: 'snake', moves: `R U R' U' R' F R2 U R' U' F'`, mirror: 'FB', invert: true },
    { name: 'cute', moves: `R' U' R U' R' U F' U F R`, mirror: 'FB', invert: true },
    // { name: 'aperm', moves: `xR'UR'D2RU'R'D2R2x'`, mirror: 'FB', invert: true },
    // { name: 'bruno', moves: `RU2R2U'R2U'R2U2R`, mirror: 'FB', invert: true },
    // { name: 'brunoswap', moves: `R U2 R' U2 R' F R2 U R' U' F'`, mirror: 'FB', invert: true },
    // { name: 'suneperm', moves: `r U M U R' U' r U' r'`, mirror: 'FB', invert: true },
    // { name: 'diagT', moves: ` R2U'RFR'UR2U'R'F'R `, mirror: 'FB', invert: true },
    // { name: 'checkcomm', moves: `L'R'D2RU2R'D2RU2L`, mirror: 'FB', invert: true },
    // { name: 'snappy', moves: `R2U'RFR'UR2U'R'F'R`, mirror: 'FB', invert: true },
    // { name: 'otherfruf', moves: `F R2 D R' U R D' R2 U' F'`, mirror: 'FB', invert: true },
    // { name: 'asdf3', moves: `F R U' R' U' R U R' F'`, mirror: 'FB', invert: true },
    // { name: 'rude', moves: `F R U' R D R' U2 R D' R2 U' F'`, mirror: 'FB', invert: true },
    // { name: 'unnamed', moves: `F R2 D R' U R D' R2 U' F'`, mirror: 'FB', invert: true },
    // { name: 'jperm', moves: `R U R' F'R U R' U' R' FR2 U' R' U'`, mirror: 'FB', invert: true },
    // { name: 'cutecomm', moves: `R2 D R' U2 R D' R' U2 R'`, mirror: 'FB', invert: false },
];
